# Generated by Django 6.0.6 on 2026-06-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='albums/%Y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.singer')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('file', models.FileField(upload_to='songs/%Y/%m')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.album')),
            ],
        ),
    ]
