# Generated by Django 6.0.6 on 2026-06-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_song_album_album_song_song_singer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='albums/%Y/%m'),
        ),
    ]
