# Generated by Django 6.0.6 on 2026-06-20 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_song_album_album_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='singer',
        ),
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
        migrations.AddField(
            model_name='singer',
            name='albums',
            field=models.ManyToManyField(blank=True, to='main.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.album'),
        ),
    ]
