# Generated by Django 6.0.6 on 2026-07-06 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_album_singer_remove_album_songs_singer_albums_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='singer',
            options={'verbose_name': 'Singer', 'verbose_name_plural': 'Singers'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='albums/%Y/%m', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='albums',
            field=models.ManyToManyField(blank=True, to='main.album', verbose_name='Albums'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.album', verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='songs/%Y/%m', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('classic', 'Classic')], max_length=100, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.singer', verbose_name='Singer'),
        ),
    ]
